# Generated by Django 5.2.8 on 2025-11-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='score',
            field=models.PositiveIntegerField(choices=[(1, 'Very bad'), (2, 'Bad'), (3, 'Normal'), (4, 'Good'), (5, 'Perfect')], max_length=8),
        ),
    ]
